version: "3"

services:
    pgsql:
        image: "postgres:12"
        ports:
            - "5432:5432"
        volumes:
            - ./pg/db_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=bm
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        networks:
            - sail
    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "3333:3333"
        volumes:
            - ./backend:/app
        networks:
            - sail
        depends_on: 
            - pgsql
    # frontend: 
    #     build: 
    #         context: ./frontend
    #         dockerfile: Dockerfile 
    #     ports: 
    #         - "3000:3000"
    #     volumes:
    #         - ./frontend:/app
networks:
    sail:
        driver: bridge
volumes:
    sailpostgresql:
        driver: local
            